/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wes (https://sketchfab.com/wimell)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/iphone-16-free-d58591e88a824dfd8cef0af616273b02
Title: iPhone 16 - Free
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import gsap from "gsap";
import { useEffect, useRef } from 'react';

type GLTFResult = GLTF & {
  nodes: {
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_62: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_77: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
  }
  materials: {
    d79c406d92ac2ea2b462: THREE.MeshPhysicalMaterial
    ['8ed052ed6d3cd71ab5e3']: THREE.MeshPhysicalMaterial
    ['5155c9eac3acd76d34a9']: THREE.MeshPhysicalMaterial
    ['4130c6244c49c5d5712e']: THREE.MeshPhysicalMaterial
    a18b462c494e4fd29b4b: THREE.MeshPhysicalMaterial
    dee5a626f928a5fa4c28: THREE.MeshPhysicalMaterial
    e73cdd81f0248824c66f: THREE.MeshPhysicalMaterial
    ['5d66e4713803a9e0ad46']: THREE.MeshPhysicalMaterial
    ['3b9594ccffa1d862f699']: THREE.MeshPhysicalMaterial
    ['3a020e0705c66463c666']: THREE.MeshPhysicalMaterial
    ['8293fe999d10eb51dc07']: THREE.MeshPhysicalMaterial
    b23162de4d8409eb15f1: THREE.MeshPhysicalMaterial
    e7fedd2cefc789ae4070: THREE.MeshPhysicalMaterial
    cf3bfd3f874c6277f037: THREE.MeshPhysicalMaterial
    ['483cd8d2505fcf4cc33c']: THREE.MeshPhysicalMaterial
    ['13fa87e9b9ea638526bb']: THREE.MeshPhysicalMaterial
    cecc91181f1dafcc19fa: THREE.MeshPhysicalMaterial
    ['2df164b7997e629e4d7e']: THREE.MeshPhysicalMaterial
    ['103fc094f5cdada7aa57']: THREE.MeshPhysicalMaterial
    ['25fa7b29639901e1f310']: THREE.MeshPhysicalMaterial
    ['299a045923a299d97c82']: THREE.MeshPhysicalMaterial
    ['82823ff934002f16e6e0']: THREE.MeshPhysicalMaterial
    b4ad12de1fcbdd61166e: THREE.MeshPhysicalMaterial
    ec12d37933cc378c1226: THREE.MeshPhysicalMaterial
    bfb52a03e58fd454437d: THREE.MeshPhysicalMaterial
    ['906edd797edf30e1b5ca']: THREE.MeshPhysicalMaterial
    c306087c056eb775dddc: THREE.MeshPhysicalMaterial
    ['4a6c96a0e91c63810afa']: THREE.MeshPhysicalMaterial
    ['4e2775e8ab652e8ec892']: THREE.MeshPhysicalMaterial
    c1f38c49c59514a1f2d9: THREE.MeshPhysicalMaterial
    b8c5608ba04260006bf0: THREE.MeshPhysicalMaterial
    ['091912dc178e0b223122']: THREE.MeshPhysicalMaterial
    ['6a2b4bcac74a0306e361']: THREE.MeshPhysicalMaterial
    f960f58dcaeee45e59c1: THREE.MeshPhysicalMaterial
    ['50c2259ef1b62ea11389']: THREE.MeshPhysicalMaterial
    ['994433e619f1f1513042']: THREE.MeshPhysicalMaterial
    ['16d76ca3cbeebab956f0']: THREE.MeshPhysicalMaterial
    ['15e105904fe114289c62']: THREE.MeshPhysicalMaterial
    a86dab30a71ca989ac8c: THREE.MeshPhysicalMaterial
  }
}

export function IPhone(props: JSX.IntrinsicElements['group']) {
      const group = useRef<THREE.Group>(null!);
    
  const { nodes, materials } = useGLTF('glb/iphone_16.glb') as GLTFResult

  const tl = gsap.timeline();

  useEffect(() => {
    tl.to(group.current.rotation, {
      // x: -1,
      y: -1.7,
      // z: 2,
      duration: 1, // スムーズな移動
      immediateRender: false, // スクロール前にリセットしない
      scrollTrigger: {
        trigger: ".page2", // Replace with your trigger element
        start: "top bottom", // When the trigger starts
        end: "top top", // When the trigger ends
        scrub: true, // Smooth scrubbing
        immediateRender: false,
        // markers: true, // Enable markers for debugging
      },
    });

    tl.to(group.current.rotation, {
      x: -1,
      z: -Math.PI * 2 - 1,
      duration: 1, // スムーズな移動
      immediateRender: false, // スクロール前にリセットしない
      scrollTrigger: {
        trigger: ".page3", // Replace with your trigger element
        start: "top bottom", // When the trigger starts
        end: "top top", // When the trigger ends
        scrub: true, // Smooth scrubbing
        immediateRender: false,
        // markers: true, // Enable markers for debugging
      },
    });

    tl.to(group.current.position, {
      x: 0,
      y: -3,
      z: 0,
      duration: 1, // スムーズな移動
      immediateRender: false, // スクロール前にリセットしない
      scrollTrigger: {
        trigger: ".page4", // Replace with your trigger element
        start: "top bottom", // When the trigger starts
        end: "top top", // When the trigger ends
        scrub: true, // Smooth scrubbing
        immediateRender: false,
        // markers: true, // Enable markers for debugging
      },
    });

    tl.to(group.current.position, {
      y: 0,
      duration: 1, // スムーズな移動
      immediateRender: false, // スクロール前にリセットしない
      scrollTrigger: {
        trigger: ".page5", // Replace with your trigger element
        start: "top bottom", // When the trigger starts
        end: "top top", // When the trigger ends
        scrub: true, // Smooth scrubbing
        immediateRender: false,
        // markers: true, // Enable markers for debugging
      },
    });
  }, []);



  return (
    <group {...props} dispose={null} ref={group}>
      <group rotation={[-Math.PI / 2, 0, 9]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_12.geometry} material={materials.d79c406d92ac2ea2b462} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['8ed052ed6d3cd71ab5e3']} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['5155c9eac3acd76d34a9']} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['4130c6244c49c5d5712e']} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.a18b462c494e4fd29b4b} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.dee5a626f928a5fa4c28} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.e73cdd81f0248824c66f} />
          <mesh geometry={nodes.Object_27.geometry} material={materials['5d66e4713803a9e0ad46']} />
          <mesh geometry={nodes.Object_29.geometry} material={materials['3b9594ccffa1d862f699']} />
          <mesh geometry={nodes.Object_31.geometry} material={materials['3a020e0705c66463c666']} />
          <mesh geometry={nodes.Object_33.geometry} material={materials['8293fe999d10eb51dc07']} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.b23162de4d8409eb15f1} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.e7fedd2cefc789ae4070} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.cf3bfd3f874c6277f037} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['483cd8d2505fcf4cc33c']} />
          <mesh geometry={nodes.Object_44.geometry} material={materials['13fa87e9b9ea638526bb']} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.cecc91181f1dafcc19fa} />
          <mesh geometry={nodes.Object_48.geometry} material={materials['2df164b7997e629e4d7e']} />
          <mesh geometry={nodes.Object_50.geometry} material={materials['103fc094f5cdada7aa57']} />
          <mesh geometry={nodes.Object_52.geometry} material={materials['25fa7b29639901e1f310']} />
          <mesh geometry={nodes.Object_54.geometry} material={materials['299a045923a299d97c82']} />
          <mesh
            geometry={nodes.Object_57.geometry}
            material={materials['82823ff934002f16e6e0']}
            position={[0, 0, 0.037]}
          />
          <mesh geometry={nodes.Object_59.geometry} material={materials.b4ad12de1fcbdd61166e} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.ec12d37933cc378c1226} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.bfb52a03e58fd454437d} />
          <mesh geometry={nodes.Object_67.geometry} material={materials['906edd797edf30e1b5ca']} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.c306087c056eb775dddc} />
          <mesh geometry={nodes.Object_72.geometry} material={materials['4a6c96a0e91c63810afa']} />
          <mesh geometry={nodes.Object_74.geometry} material={materials['4e2775e8ab652e8ec892']} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.c1f38c49c59514a1f2d9} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.b8c5608ba04260006bf0} />
          <mesh geometry={nodes.Object_82.geometry} material={materials['091912dc178e0b223122']} />
          <mesh geometry={nodes.Object_84.geometry} material={materials['6a2b4bcac74a0306e361']} />
          <mesh geometry={nodes.Object_86.geometry} material={materials.f960f58dcaeee45e59c1} />
          <mesh geometry={nodes.Object_88.geometry} material={materials['50c2259ef1b62ea11389']} />
          <mesh geometry={nodes.Object_90.geometry} material={materials['994433e619f1f1513042']} />
          <mesh geometry={nodes.Object_92.geometry} material={materials['16d76ca3cbeebab956f0']} />
          <mesh geometry={nodes.Object_94.geometry} material={materials['15e105904fe114289c62']} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.a86dab30a71ca989ac8c} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.a86dab30a71ca989ac8c} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.a86dab30a71ca989ac8c} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('glb/iphone_16.glb')